// cart
export const ADD_ITEM = 'ADD_ITEM';
export const ADJUST_ITEM_AMOUNT = 'ADJUST_ITEM_AMOUNT';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

// checkout
export const CHECKOUT_START = 'CHECKOUT_START';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';

// error
export const GENERAL_ERROR = 'GENERAL_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';
