// cart
export const ADD_ITEM = 'ADD_ITEM';
export const ADJUST_ITEM_AMOUNT = 'ADJUST_ITEM_AMOUNT';
export const DELETE_ITEM = 'DELETE_ITEM';

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
