// cart
export const ADD_ITEM = 'ADD_ITEM';
export const ADJUST_ITEM_AMOUNT = 'ADJUST_ITEM_AMOUNT';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const SYNC_PRODUCTS_INFO = 'SYNC_PRODUCTS_INFO';

// product
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const DISABLE_CHANGE_AMOUNT = 'DISABLE_CHANGE_AMOUNT';
export const ENABLE_CHANGE_AMOUNT = 'ENABLE_CHANGE_AMOUNT';

// checkout
export const CHECKOUT_START = 'CHECKOUT_START';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';

// error
export const GENERAL_ERROR = 'GENERAL_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';

// query product by id
export const QUERY_PRODUCT_START = 'QUERY_PRODUCT_START';
export const QUERY_PRODUCT_SUCCESS = 'QUERY_PRODUCT_SUCCESS';
export const QUERY_PRODUCT_FAILURE = 'QUERY_PRODUCT_FAILURE';
