// cart
export const ADD_ITEM = 'ADD_ITEM';
export const ADJUST_ITEM_AMOUNT = 'ADJUST_ITEM_AMOUNT';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

// sync product info with server
export const SYNC_PRODUCTS_INFO_START = 'SYNC_PRODUCTS_INFO_START';
export const SYNC_PRODUCTS_INFO_SUCCESS = 'SYNC_PRODUCTS_INFO_SUCCESS';
export const SYNC_PRODUCTS_INFO_FAILURE = 'SYNC_PRODUCTS_INFO_FAILURE';

// for disable changing amount
export const DO_SOMETHING_ASYNC = 'DO_SOMETHING_ASYNC';
export const DO_SOMETHING_ASYNC_SUCCESS = 'DO_SOMETHING_ASYNC_SUCCESS';

// product
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

// checkout
export const CHECKOUT_START = 'CHECKOUT_START';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';

// error
export const GENERAL_ERROR = 'GENERAL_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';

// add product tp cart
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_FAILURE = 'ADD_PRODUCT_TO_CART_FAILURE';
export const ADD_PRODUCT_TO_CART_RESET = 'ADD_PRODUCT_TO_CART_RESET';
